### ISSUE TITLE
Improve demography study

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab#155]
The current demography study has some problems:

- It's data source specific. The behaviour of how demography is calculated should be independent of the datasource type in most of the cases.
- It writes each item again. That's not necessary because only max and min dates should be updated written/updated.
- It only updates a number of items per each author. In this case 10000 but an author can have more activity data than those.

Let's improve this study fixing these issues.

**Comment by valeriocos** [comment]
Some improvements have been already integrated to the [code base](https://github.com/chaoss/grimoirelab-elk/commit/8ffd1f50e995647f0af4218f054c2ab43cebbf1c). The demography study is now generic and uses update operations to refresh the data. It can be easily plugged to any enricher, currently [git](https://github.com/chaoss/grimoirelab-elk/commit/057c10ae524d6c70619036d5363e00a7aa643d38) and [gerrit](https://github.com/chaoss/grimoirelab-elk/commit/23deeaaa0a520ff01aa169787be33d39cf5053ac) support it.

WRT the number of items to update, since I didn't find a way to iterate over paginated results of aggregations, the number has been increased and set up to [30000](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L1060).

**Comment by sduenas** [comment]
We can close this ticket then as this enhancement has been included in the code.
