### ISSUE TITLE
pip does not upgrade grimoirelab between versions

### ISSUE THREAD

**Issue by acs** [chaoss/grimoirelab#178]
Trying to upgrade my grimoirelab deployed with pip, I needed for force the upgrade.

```
(venv) acastillo@acastillo:~$ grimoirelab -v
GrimoireLab 0.2.0
(venv) acastillo@acastillo:~$ pip install grimoirelab
Requirement already satisfied: grimoirelab in ./venv/lib/python3.6/site-packages
...
(venv) acastillo@acastillo:~$ pip install grimoirelab==0.2.3
Collecting grimoirelab==0.2.3
...
Successfully installed cereslib-0.1.6 grimoire-elk-0.36.0 grimoirelab-0.2.3 grimoirelab-panels-0.0.31 kingarthur-0.1.14 manuscripts-0.2.19 perceval-0.12.5 rq-0.12.0 sirmordred-0.2.5 sortinghat-0.7.3
(venv) acastillo@acastillo:~$ grimoirelab -v
GrimoireLab 0.2.3
```

**Comment by jgbarah** [comment]
Thanks for the report. However, I'm not sure where the bug is. If I understand your scenario, you already had grimoirelab installed (version 0.2.0), and you wanted to update to the newest version. If this is the case, the way to do it with pip is:

```
pip install grimoirelab --upgrade
```

If you don't specify `--upgrade`, pip just looks for any version of `grimoirelab`, finds it already installed (0.2.0 in you case), and considers it's done. With `--upgrade` pip checks with pypi if there are newer versions, and if so, installs them.

I'm closing, just in case I'm right. But if I'm missing something, and you still consider this is still an issue, please reopen.

**Comment by acs** [comment]
Ups, I have expected that if a newer version is available, it will upgrade automatically or at least, it will mention it. My fault.

Thanks @jgbarah for the explanation.
