### ISSUE TITLE
Python 3.4?

### ISSUE THREAD

**Issue by nedbat** [chaoss/grimoirelab#196]
The setup.py classifiers list only Python 3.4 as a Python 3 version.  Is there a reason to stick with (old) Python 3.4, or are newer versions supported?

**Comment by sduenas** [comment]
Python 3.5 and 3.6 are also supported. Sorry for the mistake. I think we should add more labels to the classifiers. It works with 3.5 and 3.6 too. We couldn't test it with newer versions.

And you are right. We need to consider to deprecate the support for 3.4 during the next months since it was deprecated in March, I think.
