### ISSUE TITLE
Evaluate adding feature for qualitative analysis by Social Currency method

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#206]
At OSSNA19, [Samantha](https://www.linkedin.com/in/samanthavlogan/) introduced me to a method she is using for understanding the health of an online community, using Social Currency constructs. 

The method is:
1. Collect text (e.g., emails, comments, issues, pull requests, tweets, stack-overflow questions)
2. Tag the text with topics (e.g., bug, feature request, question, complement)
3. Tag the text with Social Currency constructs (i.e., Merit, Trust, Transparency, Utility, Consistency)
4. Display in a pivot table the number of tags used across topics and SC constructs.

The tagging is at first a manual process and requires a good understanding of the community and good definition of the SC constructs. The training and implementation of the method in an organization is Samantha's business model.

I am opening this issue, because I think GrimoireLab can support this method.
1. Perceval already collects text from 30 different data sources.
2. For the tagging, we may export the text into a spreadsheet, such as an [Airtable](https://airtable.com/) or Google Spreadsheet.
3. The analysis can be made available in two places: 1) in the spreadsheet with a pivot table. 2) in Kibiter (GrimoireLab dashboard) together with other quantitative community health metrics.

Closing condition:
- A description of how the SC method can be supported and implemented in GrimoireLab
- Requirements detailed enough for an engineer to begin building the solution
- A time estimate for implementing the feature

**Comment by valeriocos** [comment]
Hi @GeorgLink,

The idea sounds interesting, I have some questions :)

Do you have some references to read more about this method? A reference that compares/evaluates this approach with other ones (e.g., quality models) would be helpful too.

Once the method/model is trained, what does it happen with new text? It should be automatically tagged within GrimoireLab or it will be the input of Samantha's machinery?

How many times in your opinion the analysis should be executed: every time some new text appears, every month, every quarter, etc.?

Based on your initial description, a solution could be to define a study (or an external script) that creates an index with items of the following shape:
```
created_at: ...
text: ...
data_source: ...
uuid: ...
parent_uuid: ... (original perceval item)
```
This will expose the input needed by Samantha.
External scripts can take this index and perform topic and SC labeling/classification (this should be Samantha's work).
The output of the external scripts can be then used to update the index with additional attributes (e.g., topic and SC labels). The update could be scheduled every month/quarter/... or executed when needed (a button) to produce reports.

WDYT?

**Comment by GeorgLink** [comment]
I expect that we'll discuss all these things in CHAOSS meetings because I
would like this to be an official CHAOSS metric, if others agree.

I don't know all the implementation specifics at this time. We can revisit
them later.

**Comment by aserebrenik** [comment]
This sounds interesting and related to the recent work of Qiu et al. on social capital in open source projects: https://www.win.tue.nl/~aserebre/ICSE2019.pdf

Huilian Sophie Qiu, Alexander Nolte, Anita Brown, Alexander Serebrenik, Bogdan Vasilescu. Going Farther Together: The Impact of Social Capital on Sustained Participation in Open Source 41st International Conference on Software Engineering (ICSE 2019), 2019, pp. 688-699

**Comment by valeriocos** [comment]
Thank you @aserebrenik for sharing that reference, I'll read it.

**Comment by aserebrenik** [comment]
@GeorgLink Unfortunately I will not be able to attend the meeting tomorrow but it will be my pleasure to learn about your approach.

**Comment by GeorgLink** [comment]
Awesome, I will make sure to take notes during the meeting and hopefully
document a new CHAOSS metric.

**Comment by valeriocos** [comment]
It seems this issue has been opened a bit too early, since the closing conditions require some clarifications (e.g., https://github.com/chaoss/grimoirelab/issues/206#issuecomment-524630360) and the outcome of CHAOSS meetings discussions (which are still ongoing).

Although the Social Currency method is really interesting and promising, this issue should be closed (or marked as blocked) until the aformentioned requirements have been clarified. 
It would be helpful to reference the summary of the discussions about this candidate metric here.

please @sduenas share your thoughts

**Comment by GeorgLink** [comment]
I know it looks bad to have an issue open for too long 😔 

If you want to close it, that's fine.

**Comment by GeorgLink** [comment]
@aserebrenik , here is the summary from our conversation on Tuesday: https://lists.linuxfoundation.org/pipermail/chaoss/2019-August/000740.html

**Comment by aserebrenik** [comment]
@GeorgLink This sounds interesting. If "sentiment" in their discussion is similar to "sentiment" in "sentiment analysis", then there are multiple research prototype tools capable of identifying sentiment (polarity) of a software engineering text.

**Comment by samanthavenialogan** [comment]
Hello everyone,

This is Samantha of SociallyConstructed.Online (Website to come as soon as life calms down, promise!).  I've also sent this email to the mailing list as I recognize neither Dylan nor I have been around to answer some of the more pertinent questions about the Social Currency Metrics System.

Dylan and I spent some time over the meeting talking about social scientific theories, which ate into time discussing the actual Social Currency Metrics system, and we are more than happy to join you again to discuss it further. 

Until then, I thought I might answer some of the questions that had already been asked to make sure we don’t take up too much of your time:

Questions I've found (please let me know if there are others, or I missed any):

**1Q.**

> Valeriocos - Do you have some references to read more about this method? A reference that compares/evaluates this approach with other ones (e.g., quality models) would be helpful too.

**1A**.
As it stands we have plenty of resources for anthropologists due to the nature of the system. [Ethnography in virtual worlds is a great one](https://www.amazon.com/Ethnography-Virtual-Worlds-Handbook-Method/dp/0691149518/ref=asc_df_0691149518/?tag=hyprod-20&linkCode=df0&hvadid=312425492373&hvpos=1o3&hvnetw=g&hvrand=13048499255800608569&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9028838&hvtargid=pla-491969064454&psc=1), but regarding the actual SCMS, we have internal documentation that we intend to develop into something publishable in the near future. 

We are most happy to provide you access to those documents through a google drive we have set up for Chaoss and Bitergia specifically. I would prefer to do this on a person-by-person basis so as to control the flow of information a bit easier until things get published though.  To get access to all of the documentation, message Dylan or myself at [Dylan@sociallyconstructed.online](mailto:Dylan@sociallyconstructed.online) or [samantha@sociallyconstructed.online](mailto:samantha@sociallyconstructed.online) and we'll get that to anyone who is interested in seeing that documentation before it’s available publicly.

**2Q:**

>Valeriocos - How many times in your opinion should the analysis be executed: every time some new text appears, every month, every quarter, etc.? [And] Once the method/model is trained, what happens with new text? Should it be automatically tagged within GrimoireLab, or will it be the input by Samantha's machinery?

**2A:**
We touched on this a bit in the meeting, but the answer is both.  Once the model is trained, you can scale it to meet your individual needs. Community qualitative data can be more of a fire-hose than quantitative data can, and that's precisely why it's been ignored for so long. It's hard to process, with a large margin for error if you don’t know the proper way to process it. This system's ability to work around some of these pitfalls is why it should appeal to those who haven’t had the knowledge or technology to process this information before our system emerged.  But much like the [Net Promoter Score](https://en.wikipedia.org/wiki/Net_Promoter)--which is honestly one of the first implementations you should build into the SCMS with any business--the results don't matter if you're not actually reading comments.  

We recommend building healthy revision habits to keep the AI and the community happy.  This looks typically like asking each SCMS trained department member to spend 1 hour coding comments for the system out of the most recent week and then all SCMS trained people coming together for a meeting over the hour to discuss 4 things (20 minutes per):
    1. A collection of the most impactful and relevant comments over the course of the past week  (with at least 1 being a bad score)
    2. Identify what you think may be a trend in what you read and have others discuss whether it should be a metric.  No metric can be decided on unless it shows in the data for “x” number of meetings.
    3. How are the SCMS numbers? What may be causing it, and how can you act on it?
    4.  Holes in the SCMS system for the primary data analyst to look into fixing in one way.

As you continue to build week-by-week, you are building a habit of making decisions based on customer sentiment, while you're also course-correcting the AI by feeding it new training data.  When you retire a database and move to the next research period so you get week over week data, naturally the AI will improve depending on how it's built. 

I also want to clarify that we don't actually HAVE, as in own an AI yet - just what little we could get our hands on at Comcast via [Medallia](https://www.medallia.com/forrester-wave-2018/?utm_medium=Paid-Search&utm_source=Google&utm_campaign=IM-NA-Brand*2019-Scaled-NA&utm_content=Medallia_EM_KW&utm_term=medallia|e|g|c|1t1|308305874079) and through [MaxQDA](https://www.maxqda.com/qualitative-analysis-software?gclid=EAIaIQobChMIupCYyPur5AIVGP5kCh0UGgUUEAAYASAAEgLLRvD_BwE). We were planning on an opensource option and if we integrate this, it's very likely that we may ask for your assistance, if you are intrigued by the possibilities of the SCMS system.

**3Q**
> aserebrenik - This sounds interesting and related to the recent work of Qiu et al. on social capital in open source projects: https://www.win.tue.nl/~aserebre/ICSE2019.pdf

**3A**
Yes, actually it is very very similar.  The Social Currency Metric System is an amalgamation, followed by a simplification for business purposes to ensure tracking that is consistent across departments, more comfortable to follow and view, more capable of larger-scale study. the SCMS was exclusively built to meet the speed and abstract requirements of CEOs looking for bottoms lines on the health of their qualitative data funnels and ultimately, their communities, audiences, and the general message about their brand as well. 

It was built based on the following theories:
1. Social Capital Theory
2. Communication constitutes organizations theory
3. The socio-ecological model
4. The Whuffie Factor (a book by Tara Hunt)
5. My own personal theory of the 5 most vital social currency metrics
    Transparency > Utility > Consistency > Merit > Trust = Your Digital Identity's Reputation
6. Grounded theory analysis and the rule of generalization:00
    A concept applies to B studied population only so far as C limitation
7. The net promoter score and other community measurement methods
8. The 5 measurement pillars of measurementmarketing.io
9. a lot of very frustrating conversations and an epiphany about putting this all together

**4Q**
> How were the categories defined? What is the logic for choosing the tag names for categories?

**4A**
We discussed this at length in the meeting, but the short answer is, it comes out of the data itself.  It uses the social scientific method and the rule of generalization. If you notice a pattern, you start to formulate a concept and see if others studying it from outside your perspective also seem to see it. You start tracking it over a few sessions and then if the concept holds, you apply it. Then you test its application against the limitation you've set to see if it generalizes.

**5Q**

> There is a problem with people who are not trained to analyze qualitative data. There is always going to be the question of whether guidelines will be followed and the implementation will be successful.

**5A**
The entire purpose of the social currency metric system is to make the understanding of how you should approach qualitative data easy to understand and then build in to.  Using the system and teaching the SCMS the same way a person learns any other quantitative platform like google or facebook analytics, we can make this knowledge gap smaller and the rewards more empowering for the people being studied.

That said, you are right that there will always be the question of how do they know. And honestly, that's why the system is offered 100% for free by Dylan and I.  This is a system we built out of more sophisticated understanding. We stand on the shoulders of giants.  That is precisely why our entire business model is predicated on teaching, consulting, implementing in businesses over a month, and then offering further consulting services, and full-stack marketing from the point they feel comfortable. 

Our mission isn't to get people using qualitative data.  It's to get them to recognize that their community is telling a valuable story, and they currently only hear it through the footsteps quantitative data allows.

**Comment by GeorgLink** [comment]
@samanthavenialogan thank you for posting your answers here and on the CHAOSS mailing list. I will reply more fully on the mailing list, because I think we can move the discussion forward there better.

**Comment by valeriocos** [comment]
closing this issue, since the discussion has been moved elsewhere.
