### ISSUE TITLE
Problems with the docker-compose installation

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab#231]
@Virkeipa reported that she isn't able to install GrimoireLab using the [docker-compose instructions ](https://github.com/chaoss/grimoirelab#using-docker-compose). After a troubleshooting session with @zhquan @sanacl @alpgarcia , it seems that the problem is due to limited resources in her machine.

Furthermore some instructions (e.g., `sysctl -w vm.max_map_count=262144`) weren't directly accessible, since available at the [docker-compose/README.md](https://github.com/chaoss/grimoirelab/blob/master/docker-compose/README.md) but not in the main [README.md](https://github.com/chaoss/grimoirelab#using-docker-compose).

It would be great to improve the documentation with the minum requirements to run GrimoireLab safely and clarify the connection between the main README.md and the one for the docker-compose. Maybe for the latter, the main README.md should just contain a link to the docker-compose one.

Please @jsmanrique share your thougths.

**Comment by jsmanrique** [comment]
Thank you. It seems that the Requirements section in the main README.md is not clear enough:
```
Hardware: 2 CPUs, 8GB memory RAM and enough virtual memory for Elasticsearch
```

And the last part is a link to Elasticsearch documentation about the topic:
https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html

I'll try to make the requirements more prominent, because the "documentation" is already there.

What do you think?

**Comment by valeriocos** [comment]
+1, thanks!
