### ISSUE TITLE
Impossible to build the full-3p image from 0.2.38

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab#306]
Originally reported by @svdo at: https://github.com/chaoss/grimoirelab-graal/issues/86#issuecomment-595842928

```
$ docker run -v $(pwd)/build:/build -t grimoirelab/fossology-factory
Starting container: 6bbddef6ee53
Getting FOSSology source package...
dget: retrieving https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
dget: curl fossology_3.6.0-1.dsc https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc failed
Building packages...
/entrypoint.sh: line 9: cd: fossology-3.6.0: No such file or directory
debuild: fatal error at line 679:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
If FOSSology packages were built, look for them where you mounted /build
```

In other words: 404 on https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc...

**Comment by valeriocos** [comment]
The package at https://mentors.debian.net/package/fossology has been removed. As an alternative it could be possible to use http://mirrors.kernel.org/fossology/releases/3.0.0/debian/7.0/.

**Comment by valeriocos** [comment]
@vchrombie do you have time to have a look at this issue?

**Comment by vchrombie** [comment]
> @vchrombie do you have time to have a look at this issue?

Sure, @valeriocos. I have free time to work on this. Let me see more about the issue.

**Comment by valeriocos** [comment]
Thanks @vchrombie !

The problem is related with https://github.com/chaoss/grimoirelab/blob/master/third-party/entrypoint-fossology.sh, since the repo https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc isn't available anymore.

The goal is to find another way to get the debian packages below used at https://github.com/chaoss/grimoirelab/blob/master/third-party/Dockerfile-grimoirelab-3p#L17:
- /tmp/fossology-common_3.6.0-1_amd64.deb
- /tmp/fossology-nomos_3.6.0-1_amd64.deb

**Comment by vchrombie** [comment]
Hi @valeriocos 

I think I understand the issue. Since the fossology source was removed [link](https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc), the build tends to fail because of 404 error. So, we have found a new source for it, http://mirrors.kernel.org/fossology/releases/3.0.0/debian/7.0/ so it needs to be updated in grimoirelab.

I have updated the PR #317 accordingly. 
I tested it partially too. I followed the instructions at https://github.com/chaoss/grimoirelab/tree/master/third-party#example. 

It was fine untill the third instruction
```
$ docker run -v $(pwd)/build:/build -t grimoirelab/fossology-factory
```
![Screenshot_20200414_023418](https://user-images.githubusercontent.com/25265451/79161046-71090780-7df8-11ea-8cf0-035af1ed8fa1.png)

I can see that the repository was dowloaded, extracted and worked fine untill this [entrypoint-fossology.sh#L9](https://github.com/chaoss/grimoirelab/blob/master/third-party/entrypoint-fossology.sh#L9) but I couldn't see much progress after that. I tried both (y/n). Nothing worked much.

Please let me know if there is something wrong.

**Comment by valeriocos** [comment]
Hi @vchrombie sorry for the late reply. The same happens to me.

I have tried to follow also this article http://archive15.fossology.org/projects/fossology/wiki/Debian_Install_2_5, but end up with the error:
```
Get:11 http://deb.debian.org/debian stretch/main amd64 Packages [7,083 kB]
Reading package lists...
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c sudo apt-get update' returned a non-zero code: 100
```

**Comment by vchrombie** [comment]
> Hi @vchrombie sorry for the late reply. The same happens to me.

Oh. :slightly_frowning_face: 

> ```
> E: The method driver /usr/lib/apt/methods/https could not be found.
> The command '/bin/sh -c sudo apt-get update' returned a non-zero code: 100
> ```

I just googled about it and found one answer, https://askubuntu.com/a/211531. Would you like to try it once?

**Comment by vchrombie** [comment]
Let me know if you want me to experiment with anything. I can do that in my free time.

**Comment by valeriocos** [comment]
Thank you for pointing this out! Sure, give it a try @vchrombie !
