### ISSUE TITLE
Unable to group date histogram by quarter

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#319]
Hi folks,

Trying to group a date histogram by quarter but struggling - see screencap:

https://www.youtube.com/watch?v=fmIbaawSFqg

Any suggestions?

**Comment by RCheesley** [comment]
Was there any thought on how to resolve this?

**Comment by alpgarcia** [comment]
Hi @RCheesley,

I'm sorry, I didn't see this issue. I found a workaround for that, it is not perfect though.

Here is the workaround I found some time ago:

* Set the bucket as `Date Histogram` and select the field you want.
* Set `Interval` to `Custom` and `4M` (yes, longer than a quarter, this avoids possible overlappings because Kibana is going to draw the chart based on this, but translating it to days and elasticsearch is responding with real quarters, so we need Kibana to draw longer intervals to make sure bars are not going to overlap)*.
*Open `Advanced` section at the bottom and set the `JSON input` text field to: `{"interval": "quarter"}`.

![Quarters_01](https://user-images.githubusercontent.com/3502941/87397402-98689f80-c5b4-11ea-98ba-fa0a6f3f405b.png)

(*) Interval field seems to be used by Kibana to set charts width, but not passed in the underlying ES query for data (see interval within the request JSON body):
![Quarters_02](https://user-images.githubusercontent.com/3502941/87397398-97d00900-c5b4-11ea-8ef2-0f722729ee27.png)


Hope it helps!

Alberto.

**Comment by RCheesley** [comment]
Thanks for the suggestion, I'll look into that for sure!

**Comment by RCheesley** [comment]
Hi there,

This partially addresses the issue however it concerns me that this seems to suggest there is data coming in from July when it shouldn't be:

![screenshot-dashboard mautic org-2020 07 27-14_36_04](https://user-images.githubusercontent.com/2930593/88548281-d0d99600-d016-11ea-821b-561543ed0e5f.png)

**Comment by alpgarcia** [comment]
At this point, I fear this is a Kibana issue and I'm not sure whether we could find a workaround for this in the vertical bar chart visualization. Maybe timelion or Vega visualizations could provide other ways to deal with this.
