### ISSUE TITLE
GHE enterprise URLs

### ISSUE THREAD

**Issue by ZsoltPath** [chaoss/grimoirelab#335]
Hi,

I'm trying to setup a POC for our organisation in a GitHub Enterprise account.
I'm using the latest grimoirelab/full docker image on my Windows Docker desktop.
It was fine until I've just used the built in config to see the grimoirelab repos.
But when I've changed the config to our own stuff it throws errors.

My configs:
credentials.cfg
```
[github]
api-token = 13******fd
enterprise-url = https://api.github.com
```

projects.json
```
{
 "Path": {
  "git": [
   "https://github.com/rbs-path/infra-path",
   "https://github.com/rbs-path/infra-step"
  ],
  "github": [
   "https://github.com/rbs-path/infra-path",
   "https://github.com/rbs-path/infra-step"
  ]
 }
}
```

I'm getting the following errors:
`2020-06-23 08:16:26,541 - grimoire_elk.elk - ERROR - Error feeding raw from github (https://api.github.com/rbs-path/infra-step): 404 Client Error: Not Found for url: https://api.github.com/api/v3/repos/rbs-path/infra-step/issues?per_page=100&since=1970-01-01T00%3A00%3A00%2B00%3A00&direction=asc&state=all&sort=updated`

And correctly none of the above URLs are working.
https://github.com/rbs-path/infra-step is a URL which works in a browser for authenticated users.
https://api.github.com/repos/rbs-path/infra-step/issues URL is working with the token authentication.

Could you help me what should I put into the configs?

**Comment by valeriocos** [comment]
Hi @ZsoltPath ,

If your repos are on github.com, you don't need to set the `enterprise-url`. This param is needed only if the GitHub instance is hosted in a different domain. 

Since your Git repositories are private, you need to complete their URLs with a valid github login and token: `"https://<login>:<github-token>@github.com/rbs-path/infra-path"`.

An example of configs that should work are provided below:

**credentials.cfg**
```
[github]
api-token = 13******fd
```

**projects.json**
```
{
 "Path": {
  "git": [
   "https://ZsoltPath:13******fd@github.com/rbs-path/infra-path",
   "https://13******fd@github.com/rbs-path/infra-step"
  ],
  "github": [
   "https://github.com/rbs-path/infra-path",
   "https://github.com/rbs-path/infra-step"
  ]
 }
}
```

A similar issue was opened time ago: https://github.com/chaoss/grimoirelab/issues/205, the comment at https://github.com/chaoss/grimoirelab/issues/205#issuecomment-524746746 should work in your case too.

Hope this helps,
Valerio

**Comment by ZsoltPath** [comment]
Thanks @valeriocos! It works now although with other problems. 
I've commented to the linked issue instead.

**Comment by valeriocos** [comment]
You're welcome @ZsoltPath !
