### ISSUE TITLE
Include saved objects (dashboard/panels/indexes) automatically with Docker-Compose

### ISSUE THREAD

**Issue by connorlindsey** [chaoss/grimoirelab#346]
Hi,

I'm running the toolset on Docker Compose and would like to include several dashboards I've built out whenever I restart or deploy somewhere else (for example by hosting on AWS ECS). How can I automatically include saved objects I've exported? Is there a config option in setup.cfg? 

How can I reference these objects from menu.yaml as well? The default settings references panels at `panels/json/<panel_name>.json`, but that folder is not included with the grimoirelab repo. Are those downloaded when Docker is running? 

Thanks!

**Comment by valeriocos** [comment]
Hi @connorlindsey ,

This is something that isn't supported by the platform AFAIK. You could modify the code of the panels package within the mordred container, please check the steps below:
  - enter to the mordred container (`docker exec -it <mordred-container> bash`)
  - go to `/usr/local/lib/python3.5/dist-packages/panels/json`
  - add your dashboards and index patterns (if needed) there. Please note that (i) the dashboards and index patterns must be in the kidash format, (ii) the files you copy in the container must have the same permissions of the other dashboards/index patterns (iii) you can use `docker cp` to copy these files to the container.
  - modify the [menu.yml](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/menu.yaml) by expanding an existing section to include your dashboards.

This solution will automatically upload your dashboards, however you will lose these changes in case you update or recreate the container.

In case you don't want to use `docker cp`, you can modify the docker-compose by adding a volume to the mordred section. As similarly done for the setup.cfg and aliases.json (ref [here](https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml#L51-L52)), the folder containing the dashboards will be copied into the container.

If you accept a manual solution, you could use [Kidash](https://github.com/chaoss/grimoirelab-kidash#usage) to upload your panels (please note that you should install it from source code since the pypi package isn't up-to-date). If you want to modify the top menu, you can follow the instructions at: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#modify-the-menu-

Hope this helps!

**Comment by connorlindsey** [comment]
Awesome, this helps a lot. Thanks! I'll test these and will make PRs in the docs to include that information.

**Comment by valeriocos** [comment]
Great, thanks @connorlindsey !

**Comment by connorlindsey** [comment]
Hey, I'm testing out adding exported objects as a volume in docker compose and am not having much luck. Here are the steps I followed.

1. Export saved objects from Kibana (~300 objects including index patterns, visualizations, and dashboards). It exports one file
2. Added volume to mordred (`../default-grimoirelab-settings/panels/:/usr/local/lib/python3.5/dist-packages/panels/json`)
3. I added the export.json file to `../default-grimoirelab-settings/panels/` with no luck.
4. I wrote a script to copy each object from export.json into individual files like how Sigils is formatted
5. Re-ran docker-compose and am not seeing the visualizations although they are present in the container at `/usr/local/lib/python3.5/dist-packages/panels/json`. 

My goal is to not have to manually create the index patterns like in the screenshot below and not have to manually import the saved objects with Kibana. Any suggestions?

![Screen Shot 2020-07-07 at 10 51 39 AM](https://user-images.githubusercontent.com/12838032/86816433-09520980-c041-11ea-84c7-eaa16dc589d8.png)

**Comment by dlumbrer** [comment]
> Hey, I'm testing out adding exported objects as a volume in docker compose and am not having much luck. Here are the steps I followed.
> 
> 1. Export saved objects from Kibana (~300 objects including index patterns, visualizations, and dashboards). It exports one file
> 2. Added volume to mordred (`../default-grimoirelab-settings/panels/:/usr/local/lib/python3.5/dist-packages/panels/json`)
> 3. I added the export.json file to `../default-grimoirelab-settings/panels/` with no luck.
> 4. I wrote a script to copy each object from export.json into individual files like how Sigils is formatted
> 5. Re-ran docker-compose and am not seeing the visualizations although they are present in the container at `/usr/local/lib/python3.5/dist-packages/panels/json`.
> 
> My goal is to not have to manually create the index patterns like in the screenshot below and not have to manually import the saved objects with Kibana. Any suggestions?
> 
> ![Screen Shot 2020-07-07 at 10 51 39 AM](https://user-images.githubusercontent.com/12838032/86816433-09520980-c041-11ea-84c7-eaa16dc589d8.png)

Hi @connorlindsey ,

When you re-ran the docker-compose, did you delete the mordred contained before?, It's seems that because Mordred is the one who create the index patterns.

Regarding the panels, did you changed the `menu.yml` file before copying them? as @valeriocos indicated here:

> ...
>
> * modify the [menu.yml](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/menu.yaml) by expanding an existing section to include your dashboards.
>
> ...

**Comment by connorlindsey** [comment]
Hi @dlumbrer,

I ran `docker-compose down` then `docker-compose up -d`, completely restarting the containers. 

I haven't edited the `menu.yml` file yet. I'll give that a shot and see if it changes anything.

**Comment by dlumbrer** [comment]
> Hi @dlumbrer,
> 
> I ran `docker-compose down` then `docker-compose up -d`, completely restarting the containers.

`docker-compose down` stops and removes the containers. If you launch all the containers from scratch the index-pattern problem should disappear.

> 
> I haven't edited the `menu.yml` file yet. I'll give that a shot and see if it changes anything.

Please, check if the dashboards are in the `/usr/local/lib/python3.5/dist-packages/panels/json` file with the Kidash format. You can do it using `docker exec -it <container> <command>`.

Hope it helps!
