### ISSUE TITLE
Onion analysis for Git seems to have stopped

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab#353]
Possibly related to #338 - on our dashboard the onion analysis index is tiny:

![screenshot-dashboard mautic org-2020 07 03-12_38_56](https://user-images.githubusercontent.com/2930593/86465783-3e511a00-bd2a-11ea-94c0-25ca9a664f51.png)

We are not seeing the Git data in our organisation diversity and engagement panels on dashboard.mautic.org. I deleted the index at the same time as fixing #338 but it never builds larger than this.

Any ideas?

**Comment by zhquan** [comment]
Hi @RCheesley,

Could you share your projects.json and the sections `[git]` and `[enrich_onion:git]` of the setup.cfg?

It would be great if you can share the aliases of your instance too. You can execute the following command in the dev tools of Kibiter `GET _cat/aliases`, thanks.

Best,
Quan

**Comment by RCheesley** [comment]
Hi Quan,

Thanks so much for the speedy reply!

https://bin.acquia.com/?4a974f5db1810fea#HNkgWi1g7CwTHdRM8eKPSRuCKn1xvC8aJxKR3YRoDEwL here is the projects.json

https://bin.acquia.com/?1841c01019b2fe47#2WvtQvMrW9BzWccJbou7umRbQk8x6vvtkME3X3NWwdaS here are the parts of the setup.cfg relating to Git and the enriched indexes.

Here are the aliases:

![screenshot-dashboard mautic org-2020 07 03-13_39_50](https://user-images.githubusercontent.com/2930593/86470785-0ea70f80-bd34-11ea-806e-ce029ba9a741.png)

**Comment by zhquan** [comment]
Hi @RCheesley,

The value `in_index` is wrong, you are using `git-aoc_demo_enriched` instead of `git_demo_enriched`.

Try to change the `in_index` value to the git enriched index `git_demo_enriched` 
```
[enrich_onion:git]
in_index = git_demo_enriched
out_index = git-onion_demo_enriched
contribs_field = hash
```
or you can use the alias `git` and you can forget the name of the git enriched index.
```
[enrich_onion:git]
in_index = git
out_index = git-onion_demo_enriched
contribs_field = hash
```

The steps to follow:
1. Stop the mordred container
2. Remove the index `git-onion_demo_enriched`
3. Change `in_index` value
4. Restart the mordered container

I hope it helps you

Best,
Quan.

**Comment by RCheesley** [comment]
Hi there,

Thanks, perhaps someone should update the defaults set [here](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/setup.cfg#L147) as that is what I was following!  Will make a PR!

**Comment by RCheesley** [comment]
@zhquan should it be git_demo_raw rather than just git?

**Comment by RCheesley** [comment]
Still only seeing 1.7Mb and no data on the dashboards - is there something like `latest-items = false` for the enrichment process?

**Comment by zhquan** [comment]
Hi @RCheesley,

I executed the onion study and I collected 1.8Mb. What size do you expect for onion?

Size of the indexes in my test
```
yellow open git_demo_raw                            XigwGZHiRYmHQS92QeHG2A 5 1  29095     0  53.3mb  53.3mb
yellow open git_demo_enriched                       zBqMOcZpTW-aJCpM1EBZgQ 5 1  29095  2899  47.6mb  47.6mb
yellow open git-onion_demo_enriched                 hV3QmxS2Saito3c2tpfQ5Q 5 1   5674     0   1.8mb   1.8mb
```

The parameter `latest-items = false` only affect the collection phase in git (`raw_index`)

The following panels use the indexpattern `all_onion`:
- https://dashboard.mautic.org/app/kibana#/dashboard/Overall-Community-Structure
- https://dashboard.mautic.org/app/kibana#/dashboard/Community-Structure-by-Project
- https://dashboard.mautic.org/app/kibana#/dashboard/Community-Structure-by-Organization

> We are not seeing the Git data in our organization diversity and engagement panels on dashboard.mautic.org

You have to add the git enriched index (`git_demo_enriched`) to the alias `all_enriched` due to those panels use that alias.
The image you shared at https://github.com/chaoss/grimoirelab/issues/353#issuecomment-653532964 the alias `all_enriched` only has `slack_demo_enriched` and `meetup_demo_enriched`

Steps:
1. Add the index `git_demo_enriched` to the alias `all_enriched`
2. Check again the panels [Engagement](https://dashboard.mautic.org/app/kibana#/dashboard/b7b169e0-14e3-11e9-8aac-ef7fd4d8cbad) and [Organizational Diversity](https://dashboard.mautic.org/app/kibana#/dashboard/ab68fe20-17f2-11e9-872f-e17019e68d6d)

Best,
Quan

**Comment by RCheesley** [comment]
Thanks, can you point me at the documentation which explains how to add indexes to the alias with dev tools? I have not done it before (afaik).

**Comment by zhquan** [comment]
Yes of course https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

**Comment by RCheesley** [comment]
Thanks, that syntax does not seem to be accepted in dev tools though:

`POST /_aliases { "actions" : [ { "add" : { "index" : "git_demo_enriched", "alias" : "all_enriched" } } ] }`

It does not give an option to run the command?

**Comment by zhquan** [comment]
Could you click on the play button on the right side, and share the output?

![image](https://user-images.githubusercontent.com/5637233/86569585-e6572500-bf6e-11ea-94c6-728379a2b68c.png)

**Comment by RCheesley** [comment]
That was the issue, no button appeared to click as I was using the syntax above based on the article linked rather than what you have just shared. Will give that a go, thanks for your patience!

**Comment by RCheesley** [comment]
Resolved! Thank you so much!
