### ISSUE TITLE
Needed help in the technical requirement specifically for Grimoirelab within the community-handbook

### ISSUE THREAD

**Issue by jaskiratsingh2000** [chaoss/grimoirelab#391]
Hey!

I am one of the **[Google Season of Docs](https://developers.google.com/season-of-docs)** aspirants working on the "**[Community-Handbook](https://github.com/chaoss/community-handbook)**" under the CHAOSS project. 
This issue is specific around the "Development" page under the community-handbook.

As you could see in this **[link](https://chaoss-project.gitbook.io/community-handbook/development#technical-requirements)** I have laid down the technical requirements for the "all projects" under the CHAOSS. And from my understanding, the projects are more focused on Python language but I am not sure that if Grimoire lab has any other language or framework written in. Though I see within some repositories that there are some other languages too listed in the sidebar but not sure. So I wanted to ask specifically if there are any other technical requirements for this project specifically, can someone write it down under the same section with the references to pre-surf around before chiming directly into the development stuff?

Also, here is another page that reflects the **[contribution workflow](https://chaoss-project.gitbook.io/community-handbook/development/contributing-worfkflow)** followed for any technical project. So feel free to suggest changes for it as I am not technically strong enough so I would need someone help in that if there is a requirement of any addition of more technical stuff.
Below are the respective links:

- Development page link: https://chaoss-project.gitbook.io/community-handbook/development
- Contribution Workflow: https://chaoss-project.gitbook.io/community-handbook/development/contributing-worfkflow

Your help would really be appreciable. 
Thanks!

cc @sgoggins @GeorgLink

**Comment by vchrombie** [comment]
Hi @jaskiratsingh2000 
Thanks for your awesome work and it is good to see the handbook coming in good shape.

> As you could see in this **[link](https://chaoss-project.gitbook.io/community-handbook/development#technical-requirements)** I have laid down the technical requirements for the "all projects" under the CHAOSS. And from my understanding, the projects are more focused on Python language but I am not sure that if Grimoire lab has any other language or framework written in. Though I see within some repositories that there are some other languages too listed in the sidebar but not sure. So I wanted to ask specifically if there are any other technical requirements for this project specifically, can someone write it down under the same section with the references to pre-surf around before chiming directly into the development stuff?

The main language which is needed for GrimoireLab is Python. It also needs a little understanding of Elasticsearch and Kibana (Kibiter is a soft-fork of Kibana), this is good to have. Coming to frameworks, we use Django for a few components like Hastall and Bestiary, but it not required unless you are working on development of these tools.

So, if you ask me, we can add resources for Python (will check to add anything more to the existing list) and maybe a few resources for ES and Kibana. WDYT?

Also, I had one more suggestion. I can see that the grimoirelab components are listed along with the description in the doc. Is it possible to align with this, [chaoss/grimoirelab#grimoirelab-components](https://github.com/chaoss/grimoirelab#grimoirelab-components)? 
We would then have the same thing across the website, grimoirelab main repo and handbook.

> Also, here is another page that reflects the **[contribution workflow](https://chaoss-project.gitbook.io/community-handbook/development/contributing-worfkflow)** followed for any technical project. So feel free to suggest changes for it as I am not technically strong enough so I would need someone help in that if there is a requirement of any addition of more technical stuff.

I have a small suggestion here. I see that you have already mentioned about the DCO signoff. Maybe you can add about the bot-check that is mandatory on all the contributions. Also, you can add about the DCO-extension because few might contribute via GitHub UI and having all these specifications in the handbook might be necessary. You can refer to this, [#dco-and-sign-off-for-contributions](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#dco-and-sign-off-for-contributions). 

@sduenas, do you have any more suggestions?
@jaskiratsingh2000, please let us know if you need more help.

**Comment by sduenas** [comment]
I would add that we have some code in JavaScript/TypeScript.

Also, it would be nice to add this recommendations about commit messages. At least in GrimoireLab we try to follow them: https://chris.beams.io/posts/git-commit/.

**Comment by jaskiratsingh2000** [comment]
Thank you very much @vchrombie and @sduenas for chiming in. Since Its more about technical stuff so I am just leaving it on you. So feel free to go ahead an make changes in the community handbook repo. Your help would be highly appreciable.

Thanks and Regards

**Comment by vchrombie** [comment]
The PR https://github.com/chaoss/community-handbook/pull/23 is merged and I think we have enough information to get started with GrimoireLab in the handbook, so closing this issue.

Thank you @jaskiratsingh2000 for opening the issue.
