### ISSUE TITLE
Have you considered adding other languages?

### ISSUE THREAD

**Issue by No6-start** [chaoss/grimoirelab#418]

**Comment by vchrombie** [comment]
Hi @No6-start, thanks for opening the issue. I am not sure if translations were ever discussed previously, at least to my knowledge.

When you are talking about translations, I assume you are talking about the end result of the Grimoirelab i.e, the visualizations. As of now, I don't think we have the support for other languages and we don't have it on the nearby [roadmap](https://github.com/chaoss/grimoirelab/projects/1) too. But, it would be interesting to look at how Kibana has adopted this because [Kibiter](https://github.com/chaoss/grimoirelab-kibiter) (which empowers GrimoireLab Panels) is a soft-fork of Kibana. It is equally important to evaluate the amount of work and changes that are needed for this task.

I would like to listen to other community members' opinions.

**Comment by sduenas** [comment]
I think we'll be very happy of having other translations. I'm afraid we don't have good documentation neither in English nor Spanish, though. If I have to chose I'd rather have better documentation that to have another language because we won't probably have people that can write on that new language and have the documentation updated.
