### ISSUE TITLE
Delete setup.py and requirements.txt files

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab#532]
Delete these files in all the stack because we only use `pyproject.toml` now.

**Comment by vchrombie** [comment]
Hi @sduenas, I guess we have to remove the `setup.cfg` file too right? Please let me know.

**Comment by vchrombie** [comment]
Hi @sduenas, it is clear that the `setup.cfg`, `setup.py` and `requirements.txt` have to be removed. Does it makes sense to remove the `requirements_tests.txt` too?

Also, what about the `MANIFEST.in`? I guess Poetry doesn't need this since the configurations (what to include in the packages) is already present in the `pyproject.toml` file. What do you think?

**Comment by sduenas** [comment]
This was completely done.
