### ISSUE TITLE
Github traffic metrics

### ISSUE THREAD

**Issue by krokoko** [chaoss/grimoirelab#554]
Hi ! I was wondering if there is a way to get the traffic metrics from github ? https://docs.github.com/en/rest/metrics/traffic 
I don't see anything in the configuration to enable that, or maybe I missed it ?

Thanks !

**Comment by sduenas** [comment]
Sorry for out late response.

Unfortunately, GitHub traffic metrics is something that we don't support yet. Not sure if we will do it because to get these metrics, the user needs to have push permissions on the repositories, which limits the analysis for most of the people. I see it could be useful for some users though.
