### ISSUE TITLE
GitHub Data Mismatch in Grimoire using github_repo filter

### ISSUE THREAD

**Issue by maltif** [chaoss/grimoirelab#586]
I've noticed a duplication issue between GitHub and Grimoire when using the `github_repo` filter. As you can see in the attached screenshot, there are two entries for a single GitHub user, as highlighted in the image. Ideally, there should be only one row for each GitHub user. Could you please help me understand and troubleshoot this issue? Any assistance would be greatly appreciated.

![image](https://user-images.githubusercontent.com/100792545/230955887-8f763028-fbf5-4f56-882f-9e826a038a96.png)

Any help highly appreciated.

**Comment by zhquan** [comment]
Hi @maltif,

The issue here is that those users are using two different emails to make commits in different repositories. You can dig deeper on Discover (select `git` index pattern) and add these fields: `author_name`, `author_uuid`, `author_id`, `author_domain`, and `origin` to have a better view create this filter:
- field: `author_name`
- operators: `is one of`
- values: `Jaga..., jma..., Vikas..., vikash-...` (complete the names).

If they are the same user you can use SortingHat or Hatstall to merge them.

I hope it helps you.

**Comment by maltif** [comment]
Thank you very much, @zhquan , for providing clarification on this matter - it is greatly appreciated. As you pointed out, the reason for the multiple entries, as shown in the attached screenshot, is because the commits are from different `author_domain`.


![image](https://user-images.githubusercontent.com/100792545/231260889-3daea0d5-5533-4b5d-a8f4-202ff1158d7e.png)


Regarding the users, they are indeed the same. Would you kindly advise me on how to utilize SortingHat or Hatstall to merge them? I would greatly appreciate any assistance on this matter.

**Comment by maltif** [comment]
@zhquan, we are currently using the` image: grimoirelab/grimoirelab:0.7.1` docker image as defined in the `docker-compose.yml`.  Can you please confirm if the steps mentioned earlier will work with this version?

Thank you!

**Comment by zhquan** [comment]
Yes it should work

**Comment by maltif** [comment]
Thank you @zhquan for your support.
