### ISSUE TITLE
Add a MAINTAINERS.md file for the GrimoireLab project

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/grimoirelab#592]
The CHAOSS community is moving towards more transparency about who the maintainers and leaders are that have merge rights on repositories.

There is no standard format (yet). The first step is to list the people who have merge rights in a MAINTAINERS.md file. 

[edit] We only need one file in the main project repository and link to it from the other repository README.md's

**Comment by sduenas** [comment]
Not against it but we will have to review the [contributing guidelines about committers](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#committers) and vote for a new procedure.

**Comment by GeorgLink** [comment]
Thanks Santi. The MAINTAINERS.md file will become a requirement if the CHAOSS Governing Board approves the new [CHAOSS Governance document](https://docs.google.com/document/d/1BFDxbdQmov6Ax0U_opPZF6Y-DgKOXMGv8xLdBnH4RGY/edit#) that has been spearheaded by @geekygirldawn and discussed for the past weeks in the weekly meetings.

**Comment by vchrombie** [comment]
Indeed, a file containing the list of names is all we need. We can draw inspiration from [the list](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#committers) and include it in our document as an individual file.

I found a great example here: https://github.com/opensearch-project/opensearch-plugins/blob/main/MAINTAINERS.md. We could fashion something similar for our project. How does that sound to you?

To update the list of committers, we can adhere to the standard voting procedure and modify the `MAINTAINERS.md` file accordingly.

**Comment by geekygirldawn** [comment]
The example from opensearch is ok, but what it's missing is another column called "responsibilities" that gives people more insight into what area each person is responsible for. The responsibilities column might have things like: tech lead, documentation, a feature area that person works mostly in, community management. For people who work all across the project with no real area of responsibility, you can leave it blank. It would look something more like this (just an example, not accurate about what these people do):
| Name | Employer | Responsibilities |
| ----------- | ------- | -------------------------------- |
| [Santiago Dueñas](https://github.com/sduenas) | Bitergia | Tech Lead |
| [Daniel Izquierdo Cortazar](https://github.com/dicortazar) | Bitergia | |
| [Alberto Pérez García-Plaza](https://github.com/alpgarcia) | Bitergia | Manuscripts  and Sigils|

This is just another option that can help provide more transparency into who works on what parts of the project. If you feel like this is going to be too difficult to maintain, then you can go with something simpler and remove the responsibilities column.

On @sduenas's comment about updating the [CONTRIBUTING.md](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#committers) file, the only real difference between what we have in the CHAOSS governance doc and your contributing doc is that we are calling them maintainers, instead of committers, but the process / responsibilities are the same. You could change the contributing file to replace "committers" with "maintainers" or add a sentence something like this, "For the purposes of CHAOSS governance, we are using the terms committers and maintainers interchangeably." or "For the purposes of CHAOSS governance, we are using the terms committers as equivalent to maintainers."

**Comment by sduenas** [comment]
Sorry, I think I understood you wrong when I read the issue. No problem at all adding that file.

@geekygirldawn is the one you mentioned the definitive format for that file?
