### ISSUE TITLE
Add the support for the data source Mattermost

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab#68]
Slack is already supported. It might be interesting to support also Mattermost

Potential interesting info: [Mattermost API](https://api.mattermost.com/)

Already opened an [issue in grimoirelab-perceval about it](https://github.com/chaoss/grimoirelab-perceval/issues/325)

**Comment by jsmanrique** [comment]
I think this has been already solved

**Comment by valeriocos** [comment]
There are some work to do to propagate the [change](https://github.com/chaoss/grimoirelab-perceval/commit/65a5e757a7c07a2dbbe0866a455ee38f96cec5e6) on Perceval to the enricher and dashboards.

**Comment by valeriocos** [comment]
Sorry @jsmanrique you were right. This issue was about supporting mattermost.

An upcoming feature for the next release will include also details about mattermost channels. Details on:
- Perceval https://github.com/chaoss/grimoirelab-perceval/pull/562
- ELK https://github.com/chaoss/grimoirelab-elk/pull/681
- Sigils https://github.com/chaoss/grimoirelab-sigils/pull/382

![captura_51](https://user-images.githubusercontent.com/6515067/63842661-55461380-c985-11e9-948f-0e23158a1df2.png)
