### ISSUE TITLE
Assistance requested locating metric information

### ISSUE THREAD

**Issue by Illuminatian** [chaoss/grimoirelab#78]
@jgbarah 

In an effort make CHAOSS more robust, I would like to add 4 metrics that GL produces into https://github.com/chaoss/metrics/tree/master/activity-metrics. To do that, I know there has to be code that pulls and aggregates those metrics for display...can you kindly point me in that direction? The repo is very deep, and I don't know how to swim well.

**Comment by jgbarah** [comment]
Hi, @Illuminatian. I'm sorry but I'm not sure what you want to contribute. Maybe the description of four new metrcis in /activity-metrics? If so, you just need to add them there... We do that via pull requests, you can see some of them in the repo now (as closed), for example: chaoss/metrics#50 or  chaoss/metrics#51.

I don't get what you mean about "there has to be code that pulls..."

**Comment by Illuminatian** [comment]
@jgbarah 

Sorry, I might not have explained myself properly, let me try to clear it up for you.
So, I need to add 4 metrics that GrimoireLab supports into the activity metrics in CHAOSS. It can either be a new metric that doesn't exist in https://github.com/chaoss/metrics/tree/master/activity-metrics or it can be an addition to an existing metric that doesn't have a GL section underneath it.

Example https://github.com/chaoss/metrics/blob/master/activity-metrics/issues-open.md shows how GHData pulls the requisite information through a SQL query to tell how many issues are currently open. My problem as of right now is I have absolutely no idea where I should start looking to find the code that would populate that same data using GL, due to the large size of the project and all the interconnected parts.

If you could help point me in the right direction I would be greatly appreciative!

**Comment by jgbarah** [comment]
Thanks for the clarification. I find your proposal very interesting. Let me suggest to act as follows:

* Start a pull request in chaoss/metrics in the corresponding md files, with the description of the metrics.
* In the description of the pr, state that you would like to include the GrimoireLab description for the metric.
* You suggest me as reviewer, and I try to help, along with other people in CHAOSS, to see how that fits in.

What do you think? If you decide to go this way, please:

* Open a pr per metric (and maybe start with only one, until you get familiar with the procedure).
* Ensure that you suggest me as reviewer, so that I don't miss it
* In the comment, include a reference to this issue, so that people have all the context.

**Comment by jsmanrique** [comment]
Hi @illuminatian. I don't know if [panels schemas](https://github.com/chaoss/grimoirelab-sigils/tree/master/schema) might help you. 

Because GL supports many different data sources, one metric might be obtained by different means.

Each .CSV files contains the set of fields each index produced by GL has. 

For example, for "issues open":
* In [github_issues.csv](https://github.com/chaoss/grimoirelab-sigils/blob/master/schema/github_issues.csv) there is a field called `state`. Filtering by `state=open` in GL will give the metric.
* In [bugzilla.csv](https://github.com/chaoss/grimoirelab-sigils/blob/master/schema/bugzilla.csv) there's the `status` field. Filtering by `status=open` will give you the metric.
* In [maniphest.csv](https://github.com/chaoss/grimoirelab-sigils/blob/master/schema/maniphest.csv) there's the `status` field. Filtering by `status=open` in GL will give you the metric.

Perhaps, it might be nice working on mapping current CHAOSS metrics with GL data fields and associated filters to get the metrics. What do you think?
